{"name": "test03_mis_audot", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test02_mis.TestMis object at 0x000001B8A0AF85C0>\n\n    def test03_mis_audot(self):\n        # 1、调用审核文章接口\n        r = self.mis.api_mis_audit()\n        try:\n            # 2、断言\n>           Tools.common_assert(r)\n\nscripts\\test02_mis.py:52: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tools.tools.Tools'>, response = <Response [405]>, status_code = 201\n\n    @classmethod\n    def common_assert(cls, response, status_code=201):\n        log.info(\"正在调用公共断言方法！\")\n        # 断言状态码\n        print(\"审核文章状态码：{}\".format(response))\n>       assert status_code == response.status_code\nE       AssertionError\n\ntools\\tools.py:23: AssertionError"}, "attachments": [{"name": "log", "source": "d7b51883-6a8f-4f83-a4b2-15713205c87b-attachment.txt", "type": "text/plain"}], "start": 1639840307633, "stop": 1639840307793, "uuid": "1b578db9-bf86-41da-a5e3-0eac7b61e2ea", "historyId": "796feca9a07bf298c8885dafa3f0b9a5", "testCaseId": "d85aa8cf95a03cc4c420383e3a35a80d", "fullName": "scripts.test02_mis.TestMis#test03_mis_audot", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test02_mis"}, {"name": "subSuite", "value": "TestMis"}, {"name": "host", "value": "My-fzj-pc"}, {"name": "thread", "value": "5224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test02_mis"}]}